rango/urls.py
from django.conf.urls import url
from rango import views

app_name = 'rango'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/',views.about,name='about'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$',views.show_category, name='show_category'),
    url(r'add_category/$',views.add_category,name='add_category'),
    url(r'category/(?P<category_name_slug>[\w\-]+)/add_page/$',views.add_page,name = 'add_page'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$',views.user_login, name='login'),
    url(r'^restricted/', views.restricted, name='restricted'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^goto/$', views.track_url, name='goto'),

]

tango_with_django/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from registration.backends.simple.views import RegistrationView

from rango import views
# Create a new class that redirects the user to the index page,
#if successful at logging
class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return '/rango/'

urlpatterns = [
    url(r'^$',views.index, name='index'),
    url(r'^rango/',include('rango.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/register/$',
    MyRegistrationView.as_view(),
    name='registration_register'),
    url(r'^admin/', admin.site.urls),
]

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)
    def __str__(self): # For Python 2, use __unicode__ too
     return self.name

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
         return self.name

class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)
    def __str__(self): # For Python 2, use __unicode__ too
        return self.title


class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User)
    # The additional attributes we wish to include.
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)
    # Override the __unicode__() method to return out something meaningful!
    # Remember if you use Python 2.7.x, define __unicode__ too!
    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from django.contrib.auth.models import User

from rango.models import Category, Page, UserProfile


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128,   help_text = "Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    # An inline class to provide additional information on the form.
    #  class Meta:
    # Provide an association between the ModelForm and a model
    class Meta:
        model = Category
        fields = ('name',)
class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,help_text = "Please enter the title of the page.")
    url = forms.URLField(max_length=200,help_text = "Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    # def clean(self):
    #     cleaned_data = self.cleaned_data
    #     url = cleaned_data.get('url')
    #
    #
    #     if url and not url.startwith('http://'):
    #         url = 'http://' + url
    #         cleaned_data['url'] = url
    #
    #         return cleaned_data



    class Meta:

        # Provide an association between the ModelForm and a model

        model = Page

        # What fields do we want to include in our form?
        # This way we don't need every field in the model present.
        # Some fields may allow NULL values, so we may not want to include them.
        #  Here, we are hiding the foreign key.
        # we can either exclude the category field from the form,

        exclude = ('category',)

        # or specify the fields to include (i.e. not include the category field)
        #  fields = ('title', 'url', 'views')


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password')
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

rango/views.py
from datetime import datetime

from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from rango.forms import CategoryForm, PageForm
from rango.forms import UserForm, UserProfileForm
from rango.models import Category, Page
from rango.webhose_search import run_query

def index(request):
    # A helper method
    # A helper method
    def get_server_side_cookie(request, cookie, default_val=None):
        val = request.session.get(cookie)
        if not val:
            val = default_val
        return val

    # Updated the function definition
    def visitor_cookie_handler(request):
        visits = int(get_server_side_cookie(request, 'visits', '1'))

        last_visit_cookie = get_server_side_cookie(request,
                                               'last_visit',
                                               str(datetime.now()))
        last_visit_time = datetime.strptime(last_visit_cookie[:-7],
                                            '%Y-%m-%d %H:%M:%S')
        # If it's been more than a day since the last visit...
        if (datetime.now() - last_visit_time).seconds > 0:
            visits = visits + 1
    # update the last visit cookie now that we have updated the count
            request.session['last_visit'] = str(datetime.now())
        else:
    # set the last visit cookie
            request.session['last_visit'] = last_visit_cookie
    # Update/set the visits cookie
        request.session['visits'] = visits


    request.session.set_test_cookie()
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    context_dict = {'categories': category_list, 'pages': page_list}
    # Obtain our Response object early so we can add cookie information.
    # Call function to handle the cookies
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']

    response = render(request, 'rango/index.html', context_dict)
    # Return response back to the user, updating any cookies that need changed.
    return response

def about(request):
    request.session.delete_test_cookie()
    return HttpResponse("rango says hello in about page!")

def show_category(request, category_name_slug):
    context_dict = {}

    try:
    # Can we find a category name slug with the given name?
    # If we can't, the .get() method raises a DoesNotExist exception.
    # So the .get() method returns one model instance or raises an exception.
        category = Category.objects.get(slug=category_name_slug)

    # Retrieve all of the associated pages.
    # Note that filter() will return a list of page objects or an empty list
        pages = Page.objects.filter(category=category).order_by('-views')

        context_dict['pages']=pages
        context_dict['category']=category
    except Category.DoesNotExist:
        context_dict['category']= None
        context_dict['pages']= None

    context_dict['query'] = category.name

    result_list = []
    if request.method == 'POST':
        query = request.POST['query'].strip()

        if query:

            result_list = run_query(query)
            context_dict['query'] = query
            context_dict['result_list'] = result_list
    return render(request, 'rango/category.html', context_dict)

def add_category(request):
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():

        #have we been provided with a valid form?
            form.save(commit=True)
        # Now that the category is saved
        # We could give a confirmation message
        # But since the most recent category added is on the index page
        # Then we can direct the user back to the index page.

            return index(request)
        else:
            print(form.errors)

    return render(request, 'rango/add_category.html', {'form':form})

def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return show_category(request, category_name_slug)
            else:
                print(form.errors)

    context_dict = {'form':form,'category':category}
    return render (request, 'rango/add_page.html',context_dict)


def register(request):
    # A boolean value for telling the template
    # whether the registration was successful.
    # Set to False initially. Code changes value to
    # True when registration succeeds.
    registered = False
    # If it's a HTTP POST, we're interested in processing form data.
    if request.method == 'POST':
    # Attempt to grab information from the raw form information.
    # Note that we make use of both UserForm and UserProfileForm.
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)
        # If the two forms are valid...
        if user_form.is_valid() and profile_form.is_valid():
    # Save the user's form data to the database.
            user = user_form.save()
    # Now we hash the password with the set_password method.
    # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()
    # Now sort out the UserProfile instance.
    # Since we need to set the user attribute ourselves,
    # we set commit=False. This delays saving the model
    # until we're ready to avoid integrity problems.
            profile = profile_form.save(commit=False)
            profile.user = user
    #Did the user provide a profile picture?
    # If so, we need to get it from the input form and
    #put it in the UserProfile model.
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
    # Now we save the UserProfile model instance.
            profile.save()
    # Update our variable to indicate that the template
    # registration was successful.
            registered = True
        else:
    # Invalid form or forms - mistakes or something else?
    # Print problems to the terminal.
            print(user_form.errors, profile_form.errors)
    else:
    # Not a HTTP POST, so we render our form using two ModelForm instances.
    # These forms will be blank, ready for user input.
        user_form = UserForm()
        profile_form = UserProfileForm()
    # Render the template depending on the context.
        return render(request,'rango/register.html',
            {'user_form': user_form,
            'profile_form': profile_form,
             'registered': registered})


def user_login(request):
    # If the request is a HTTP POST, try to pull out the relevant information
    if request.method == 'POST':
    # Gather the username and password provided by the user.
    # This information is obtained from the login form.
    # We use request.POST.get('<variable>') as opposed
    # to request.POST['<variable>'], because the
    # request.POST.get('<variable>') returns None if the
    # value does not exist, while request.POST['<variable>']
    # will raise a KeyError exception.
        username = request.POST.get('username')
        password = request.POST.get('password')

    # Use Django's machinery to attempt to see if the username/password
    # combination is valid - a User object is returned if it is.
        user = authenticate(username=username, password=password)
    # If we have a User object, the details are correct.
    # If None (Python's way of representing the absence of a value), no user
    # with matching credentials was found.
        if user:
        # Is the account active? It could have been disabled.
            if user.is_active:
        # If the account is valid and active, we can log the user in.
        # We'll send the user back to the homepage.
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
        # An inactive account was used - no logging in
                return HttpResponse("Your Rango account is disabled.")
        else:
        # Bad login details were provided. So we can't log the user in.
             print("Invalid login details: {0}, {1}".format(username, password))
             return HttpResponse("Invalid login details supplied.")
    # The request is not a HTTP POST, so display the login form.
    # This scenario would most likely be a HTTP GET.
    else:
    # No context variables to pass to the template system, hence the
    # blank dictionary object...
        return render(request, 'rango/login.html', {})

# Use the login_required() decorator to ensure only those logged in can access the view.
@login_required
def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    logout(request)
    # Take the user back to the homepage.
    return HttpResponseRedirect(reverse('index'))
@login_required
def restricted(request):
        return HttpResponse("Since you're logged in, you can see this text!")

def search(request):
    result_list = []

    if request.method =='POST':
        query = request.POST['query'].strip()
        if query:
            result_list = run_query(query)

    return render(request, 'rango/search.html', {'result_list': result_list})

def track_url(request):
    page_id = None
    url = '/rango/'
    if request.method == 'GET':
        if 'page_id' in request.GET:
            page_id = request.GET['page_id']
            try:

templates/rango/add_category.html
{% extends "rango/base.html" %}
{% block title %}Add Category{% endblock %}
{% block body_block %}
    <div>
        <form id="category_form" method="post" action="/rango/add_category/">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}<br/>
                {{ field }}<br/>
            {% endfor %}
        <br/>
        <button class="btn btn-primary" type="submit" name="submit"> Add Category </button>
        </form>
    </div>
{% endblock %}

templates/rango/add_page.html
{% extends "rango/base.html" %}
{% block title %}Add Page{% endblock %}
{% block body_block %}
{% if category %}
<form role="form" id="page_form" method="post"
action="/rango/category/{{category.slug}}/add_page/">
<h2 class="form-signin-heading"> Add a Page to
<a href="/rango/category/{{category.slug}}/">
{{ category.name }}</a></h2>
{% csrf_token %}
{% for hidden in form.hidden_fields %}
{{ hidden }}
{% endfor %}
{% for field in form.visible_fields %}
{{ field.errors }}
{{ field.help_text }}<br/>
{{ field }}<br/>
{% endfor %}
<br/>
<button class="btn btn-primary"
type="submit" name="submit">
Add Page
</button>
</form>
{% else %}
<p>This category does not exist.</p>
{% endif %}
{% endblock %}

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width,
initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" href="{% static 'images/favicon.ico' %}">
<title>
Rango - {% block title %}How to Tango with Django!{% endblock %}
</title>
<!-- Bootstrap core CSS -->
<link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css"
rel="stylesheet">
<!-- Custom styles for this template -->
<link href=
"http://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css"
rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
<button type="button" class="navbar-toggler hidden-sm-up"
data-toggle="collapse" data-target="#navbar"
aria-expanded="false" aria-controls="navbar">
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<a class="navbar-brand" href="#">Rango</a>
<div id="navbar">
<nav class="nav navbar-nav pull-xs-left">
<a class="nav-item nav-link" href="{% url 'rango:index' %}">Home</a>
<a class="nav-item nav-link" href="{% url 'rango:about' %}">About</a>
{% if user.is_authenticated %}
    <a class="nav-item nav-link"
href="{% url 'rango:add_category' %}">
Add a New Category</a>
<a class="nav-item nav-link"
href="{% url 'auth_logout' %}?next=/rango/">Logout</a>
{% else %}
<a class="nav-item nav-link"
href="{% url 'registration_register' %}">Register Here</a>
<a class="nav-item nav-link"
href="{% url 'auth_login' %}">Login</a>
{% endif %}
</nav>
</div>
</nav>
<div class="container-fluid">
<div class="row">

<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
{% block body_block %}{% endblock %}
</div>
</div>
</div>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script
src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js">
</script>
<script
src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js">
</script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script
src=
"http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.j\
s">
</script>
</body>
</html>

templates/rango/base_bootstrap.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width,
initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" href="{% static 'images/favicon.ico' %}">
<title>
Rango - {% block title %}How to Tango with Django!{% endblock %}
</title>
<!-- Bootstrap core CSS -->
<link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css"
rel="stylesheet">
<!-- Custom styles for this template -->
<link href=
"http://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css"
rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-dark navbar-fixed-top bg-inverse">
<button type="button" class="navbar-toggler hidden-sm-up"
data-toggle="collapse" data-target="#navbar"
aria-expanded="false" aria-controls="navbar">
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<a class="navbar-brand" href="#">Rango</a>
<div id="navbar">
<nav class="nav navbar-nav pull-xs-left">
<a class="nav-item nav-link" href="{% url 'rango:index' %}">Home</a>
<a class="nav-item nav-link" href="{% url 'rango:about' %}">About</a>
{% if user.is_authenticated %}
    <a class="nav-item nav-link"
href="{% url 'rango:add_category' %}">
Add a New Category</a>
<a class="nav-item nav-link"
href="{% url 'auth_logout' %}?next=/rango/">Logout</a>
{% else %}
<a class="nav-item nav-link"
href="{% url 'registration_register' %}">Register Here</a>
<a class="nav-item nav-link"
href="{% url 'auth_login' %}">Login</a>
{% endif %}
</nav>
</div>
</nav>
<div class="container-fluid">
<div class="row">
<div class="col-sm-3 col-md-2 sidebar">
{% block sidebar_block %}
{% get_category_list category %}
{% endblock %}
</div>
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
{% block body_block %}{% endblock %}
</div>
</div>
</div>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script
src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js">
</script>
<script
src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js">
</script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script
src=
"http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.j\
s">
</script>
</body>
</html>

templates/rango/category.html
{% extends 'rango/../rango/base.html' %}
{% load staticfiles %}
    {% block title_block %}
        {{ category.name }}
{% endblock %}

{% block body_block %}
    {% if category %}
        <h1>{{ category.name }}</h1>
        {% if pages %}
            <ul> {% for page in pages %}
            <li>
            <a href="{% url 'rango:goto' %}?page_id={{page.id}}">{{ page.title }}</a>
            {% if page.views > 1 %}
            ({{ page.views }} views)
            {% elif page.views == 1 %}
                ({{ page.views }} view)
            {% endif %}
            </li>
            {% endfor %}
            </ul>
            {% else %}
            <strong> No pages currently in category</strong>
            {% endif %}
        <a href="/rango/category/{{category.slug}}/add_page/">Add Page</a><br/>
    {% else %}
        The category does not exist
    {% endif %}
    <div>
        <h1>Search with Rango</h1>
        <br/>
        <form class="form-inline" id="user_form"
            method="post" action="{% url 'rango:show_category' category.slug %}">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" type="text" size="50"
            name="query" value="{{ query }}" id="query" />
        </div>
        <button class="btn btn-primary" type="submit" name="submit"
        value="Search">Search</button>
        </form>
    <div>
        {% if user.authenticated %}
        {% if result_list %}

        <h3>Results</h3>
        <!-- Display search results in an ordered list -->
        <div class="list-group">
        {% for result in result_list %}
        <div class="list-group-item">
            <h4 class="list-group-item-heading">
                <a href="{{ result.link }}">{{ result.title }}</a>
            </h4>
            <p class="list-group-item-text">{{ result.summary }}</p>
        </div>
        {% endfor %}
        </div>
        {% endif %}
        {% endif %}
</div>
</div>
{% endblock %}

templates/rango/cats.html
{% for c in cats %}
{% if c == act_cat %}
<li>
<strong>
<a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
</strong>
</li>
{% else %}
<li>
<a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
</li>
{% endif %}
{% endfor %}

templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
Index
{% endblock %}
{% block body_block %}
<div class="jumbotron">
<h1 class="display-3">Rango says...</h1>
{% if user.is_authenticated %}
<h1>hey there {{ user.username }}!</h1>
{% else %}
<h1>hey there partner! </h1>
{% endif %}
</div>
<div class="row marketing">
<div class="col-lg-6">
<h4>Most Liked Categories</h4>
<p>
{% if categories %}
<ul>
{% for category in categories %}
<li><a href="{% url 'rango:show_category' category.slug %}">
{{ category.name }}</a></li>
{% endfor %}
</ul>
{% else %}
<strong>There are no categories present.</strong>
{% endif %}
</p>
</div>
<div class="col-lg-6">
    <h4>Most Viewed Pages</h4>
<p>
{% if pages %}
<ul>
{% for page in pages %}
<li><a href="{{ page.url }}">{{ page.title }}</a></li>
{% endfor %}
</ul>
{% else %}
<strong>There are no categories present.</strong>
{% endif %}
</p>
</div>
</div>
<img src="{% static "images/rango.jpg" %}" alt="Picture of Rango" />
{% endblock %}

templates/rango/list_profiles.html
{% extends 'rango/base_bootstrap.html' %}
{% load staticfiles %}
{% block title %}User Profiles{% endblock %}
    {% block body_block %}
    <h1>User Profiles</h1>
    <div class="panel">
    {% if userprofile_list %}
    <div class="panel-heading">
    <!-- Display search results in an ordered list -->
    <div class="panel-body">
    <div class="list-group">
    {% for listuser in userprofile_list %}
    <div class="list-group-item">
         <h4 class="list-group-item-heading">
        <a href="{% url 'rango:profile' listuser.user.username %}">
        {{ listuser.user.username }}</a>
        </h4>
    </div>
    {% endfor %}
    </div>
    </div>
    </div>
        {% else %}
        <p>There are no users for the site.</p>
        {% endif %}
        </div>
{% endblock %}

templates/rango/login.html
{% extends 'rango/../rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
<h1>Login to Rango</h1>
<form id="login_form" method="post" action="{% url 'rango:login' %}">
    {% csrf_token %}
    Username: <input type="text" name="username" value="" size="50">
    <br/>
    Password: <input type="password" name="password" value="" size="50">
    <br/>
    <input type="submit" value="submit"/>
</form>
{% endblock %}

templates/rango/profile.html
{% extends 'rango/base.html' %}

{% load staticfiles %}

{% block title %} {{ selecteduser.username }} Profile {% endblock %}

{% block body_block %}

<h1>{{selecteduser.username}} Profile</h1>
    <img src="{{ MEDIA_URL }}{{userprofile.picture }}"
    width="300"
    height="300"
    alt="{{selecteduser.username}}" />
<br/>
<div>
    {% if selecteduser.username == user.username %}
        <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update" />
        </form>
        {% else %}
        <p><strong>Website:</strong> <a href="{{userprofile.website}}">
        {{userprofile.website}}</a></p>
    {% endif %}
</div>
<div id="edit_profile"></div>
{% endblock %}

templates/rango/profile_registration.html
{% extends "rango/base.html" %}
{% block title_block %}
    Registration - Step 2
{% endblock %}

{% block body_block %}
    <h1>Registration - Step 2</h1>
    <form method="post" action="." enctype="multipart/form-data">
    { % csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
    </form>
{% endblock %}

templates/rango/register.html
{% extends 'rango/../rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Rango
{% endblock %}

{% block body_block %}

    {% if registered %}
        Rango says: <strong>thank you for the registration</strong>
        <a href={% url 'rango:index' %}>Return to the homepage</a>
        {% else %}
        Rango says: <strong>Register here</strong><br/>
        <form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">

        {% csrf_token %}

        {{ user_form.as_p }}
        {{ profile_form.as_p }}

        <input type="submit" name="submit" value="Register"/>
        </form>
    {% endif %}
{% endblock %}

templates/rango/search.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

    {% block body_block %}
    <div>
        <h1>Search with Rango</h1>
        <br/>
        <form class="form-inline" id="user_form"
            method="post" action="{% url 'rango:show_category' category.slug %}">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" type="text" size="50"
            name="query" value="{{ query }}" id="query" />
        </div>
        <button class="btn btn-primary" type="submit" name="submit"
        value="Search">Search</button>
        </form>
    <div>
        {% if user.authenticated %}
        {% if result_list %}

        <h3>Results</h3>
        <!-- Display search results in an ordered list -->
        <div class="list-group">
        {% for result in result_list %}
        <div class="list-group-item">
            <h4 class="list-group-item-heading">
                <a href="{{ result.link }}">{{ result.title }}</a>
            </h4>
            <p class="list-group-item-text">{{ result.summary }}</p>
        </div>
        {% endfor %}
        </div>
        {% endif %}
        {% endif %}
</div>
</div>
{% endblock %}